apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquid-indexer
  labels:
    app: liquid-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liquid-indexer
  template:
    metadata:
      labels:
        app: liquid-indexer
    spec:
      containers:
        - name: liquid-indexer
          image: liquid-indexer-ecr:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: liquid-indexer-k8s-secret
          ports:
            - containerPort: 3006
          readinessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 10
            periodSeconds: 15
