apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        iamRole:
          name: arn:aws:iam::445567075963:role/eks-external-secrets-role

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: liquid-indexer-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: liquid-indexer-k8s-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dev/liquid-indexer
