apiVersion: v1
kind: Service
metadata:
  name: liquid-indexer-prod-service
spec:
  selector:
    app: liquid-indexer-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3006
  type: LoadBalancer