apiVersion: v1
kind: Service
metadata:
  name: liquid-strategy-prod-service
spec:
  selector:
    app: liquid-strategy-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP